{{- if .Values.airflow.dags.dag_share }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-dags
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: dags
    spec:
      restartPolicy: Always
      containers:
      - name: dags
        image: ubuntu:latest
        imagePullPolicy: Always
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        volumeMounts:
          - mountPath: /usr/local/airflow/dags
            name: dag
            {{- if .Values.airflow.dags.subpath }}
            subPath: {{ .Values.airflow.dags.subpath }}
            {{- end }}
      volumes:
      - name: dag
{{- if .Values.airflow.dags.persistence.enabled }}
        {{- if .Values.airflow.dags.persistence.fromProvider }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
        {{- else }}
{{ toYaml .Values.airflow.dags.persistence.volume | indent 8 }}
        {{- end }}
{{- else }}
        emptyDir: {}
{{- end }}
{{- end }}