apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.airflow.service_type }}
  selector:
    app: {{ template "fullname" . }}
    tier: web
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: web
