apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-flower
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.airflow.service_type }}
  selector:
    app: {{ template "fullname" . }}
    tier: flower
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      targetPort: flower
