apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-init
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-init
      labels:
        app: {{ template "fullname" . }}
        tier: init-db
    spec:
      containers:
      - name: airflow
        image: {{ .Values.airflow.image }}
        env:
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: POSTGRES_PWD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: postgres-password
        - name: POSTGRES_PWD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: postgres-password
        - name: RABBITMQ_PWD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: rabbitmq-password
        - name: AIRFLOW_FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: airflow-fernet-key
        - name: AIRFLOW_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: airflow-secret-key
        - name: SMTP_PWD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: airflow-smtp-password
        volumeMounts:
          - mountPath: /usr/local/airflow/confgen
            name: config
        args: ["initdb"]
        imagePullPolicy: Always
      restartPolicy: OnFailure
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}
          items:
          - key:  airflow-conf.sh
            path: airflow-conf.sh
