{{- if .Values.tls_seret.enabled }}
apiVersion: v1
data:
  tls.crt: {{ .Values.tls_seret.crt }}
  tls.key: {{ .Values.tls_seret.key }}
kind: Secret
metadata:
  name: {{ template "fullname" . }}-tls
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
{{- end }}
