apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  labels:
    app: airflow
    component: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:4.0.8
          command: ["redis-server", "/etc/redis/redis.conf"]
          ports:
          - containerPort: 6379
          volumeMounts:
          - mountPath: /etc/redis
            name: config
      volumes:
      - name: config
        configMap:
          name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
          items:
          - key: redis.conf
            path: redis.conf
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: "redis-storage"
        {{- else }}
        emptyDir: {}
        {{- end -}}
