apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
spec:
  selector:
    app: airflow
    component: redis
  ports:
  - port: 6379
    targetPort: 6379
